In [29]:
#import librarires
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.metrics import accuracy_score

In [30]:
df = pd.read_excel('churn_dataset.xlsx')
print(df.info())
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     100 non-null    int64
 1   Tenure  100 non-null    int64
 2   Sex     100 non-null    object
 3   Churn   100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB
None

   Age  Tenure     Sex Churn
0   56       8    Male    No
1   46      63  Female    No
2   32      11  Female    No
3   60       8    Male    No
4   25      35    Male    No

In [31]:
df.describe()

             Age     Tenure
count  100.00000  100.00000
mean    40.88000   35.03000
std     13.99082   21.65732
min     18.00000    1.00000
25%     30.50000   14.75000
50%     41.00000   35.00000
75%     53.25000   54.25000
max     64.00000   71.00000

In [37]:
df['Sex'] = df['Sex'].replace({'Male':1 , 'Female':0})
df['Churn'] = df['Churn'].replace({'Yes': 1 , 'No':0})

C:\Users\qappa\AppData\Local\Temp\ipykernel_16808\2766236003.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Sex'] = df['Sex'].replace({'Male':1 , 'Female':0})
C:\Users\qappa\AppData\Local\Temp\ipykernel_16808\2766236003.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Churn'] = df['Churn'].replace({'Yes': 1 , 'No':0})

In [38]:
x = df[['Age','Tenure','Sex']]
y = df['Churn']

In [39]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3 , random_state = 21)
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 70 entries, 21 to 73
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     70 non-null     int64
 1   Tenure  70 non-null     int64
 2   Sex     70 non-null     int64
dtypes: int64(3)
memory usage: 2.2 KB

In [40]:
# Gaussian Naive Bayes Model
model_gnb = GaussianNB()
model_gnb.fit(x_train, y_train)

GaussianNB()

In [42]:
y_preds = model_gnb.predict(x_test)

In [44]:
print("Accuracy:", accuracy_score(y_test, y_preds))

Accuracy: 0.8333333333333334